"""
Downloads frontend libs (Bootstrap, jQuery) and optionally HuggingFace ONNX models.

Usage:
  podman compose run --rm downloader          # full download (libs + ONNX models)
  podman compose run --rm downloader --libs-only  # only Bootstrap + jQuery (no models)
"""

import io
import json
import os
import shutil
import sys
import tarfile
import urllib.request

LIBS_DIR   = "/downloads/libs"
MODELS_DIR = "/downloads/models"

LIBS_ONLY = "--libs-only" in sys.argv

# ── helpers ───────────────────────────────────────────────────────────────────

def fetch(url: str, label: str) -> bytes:
    print(f"  GET {label} … ", end="", flush=True)
    req = urllib.request.Request(url, headers={"Accept": "*/*", "User-Agent": "python-downloader/1.0"})
    with urllib.request.urlopen(req, timeout=120) as r:
        data = r.read()
    print(f"OK ({len(data) // 1024} KB)")
    return data


# ── frontend libs (Bootstrap, jQuery) ────────────────────────────────────────

FRONTEND_LIBS = [
    ("https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css",    "bootstrap.min.css"),
    ("https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js", "bootstrap.bundle.min.js"),
    ("https://code.jquery.com/jquery-3.7.1.min.js",                                "jquery.min.js"),
]

def download_frontend_libs():
    print("\n[Bootstrap + jQuery]")
    os.makedirs(LIBS_DIR, exist_ok=True)
    for url, filename in FRONTEND_LIBS:
        dest = os.path.join(LIBS_DIR, filename)
        if os.path.exists(dest):
            print(f"  {filename} already exists — skipping")
            continue
        data = fetch(url, filename)
        with open(dest, "wb") as f:
            f.write(data)


# ── transformers.js (only for full mode) ─────────────────────────────────────

def _extract_dist_files(tarball_data: bytes, label: str) -> int:
    extracted = 0
    with tarfile.open(fileobj=io.BytesIO(tarball_data), mode="r:gz") as tar:
        for member in tar.getmembers():
            if not member.name.startswith("package/dist/"):
                continue
            filename = os.path.basename(member.name)
            if not filename:
                continue
            ext = os.path.splitext(filename)[1]
            if ext not in (".js", ".mjs", ".wasm"):
                continue
            f = tar.extractfile(member)
            if f is None:
                continue
            dest = os.path.join(LIBS_DIR, filename)
            with open(dest, "wb") as out:
                out.write(f.read())
            print(f"  [{label}] {filename}")
            extracted += 1
    return extracted


def download_transformers_js():
    print("\n[transformers.js + onnxruntime-web]")
    if os.path.exists(LIBS_DIR):
        shutil.rmtree(LIBS_DIR)
    os.makedirs(LIBS_DIR)
    total = 0
    info = json.loads(fetch(
        "https://registry.npmjs.org/@huggingface/transformers/latest", "transformers registry"
    ))
    print(f"  @huggingface/transformers v{info['version']}")
    total += _extract_dist_files(fetch(info["dist"]["tarball"], "transformers tarball"), "transformers")
    ort_info = json.loads(fetch(
        "https://registry.npmjs.org/onnxruntime-web/latest", "ort registry"
    ))
    print(f"  onnxruntime-web v{ort_info['version']}")
    total += _extract_dist_files(fetch(ort_info["dist"]["tarball"], "ort tarball"), "ort")
    print(f"\n  Done — {total} files → {LIBS_DIR}")


# ── models ────────────────────────────────────────────────────────────────────

def download_model(model_id: str, index: int, total: int):
    from huggingface_hub import snapshot_download
    print(f"\n[{index}/{total}] {model_id}")
    org, name = model_id.split("/", 1)
    local_dir = os.path.join(MODELS_DIR, org, name)
    os.makedirs(local_dir, exist_ok=True)
    snapshot_download(
        repo_id=model_id,
        local_dir=local_dir,
        local_dir_use_symlinks=False,
        token=os.environ.get("HF_TOKEN") or None,
        allow_patterns=[
            "*.json", "*.txt",
            "onnx/model_q4.onnx", "onnx/model_q4f16.onnx",
            "onnx/model_quantized.onnx", "model_quantized.onnx",
            "onnx/*.onnx_data",
        ],
    )
    print(f"  Done → {local_dir}")


def write_models_available(model_ids: list):
    lines = ["// Auto-generated by download.py — do not edit manually",
             "export const AVAILABLE_MODELS = ["]
    for mid in model_ids:
        lines.append(f'  "{mid}",')
    lines += ["];", ""]
    dest = os.path.join("/downloads", "models-available.js")
    with open(dest, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"\n  Wrote {dest} ({len(model_ids)} model(s))")


# ── main ──────────────────────────────────────────────────────────────────────

def main():
    if LIBS_ONLY:
        print("=== libs-only mode: downloading Bootstrap + jQuery ===")
        try:
            download_frontend_libs()
        except Exception as e:
            print(f"ERROR: {e}", file=sys.stderr)
            sys.exit(1)
        print("\nDone.")
        return

    # Full mode: transformers.js + frontend libs + ONNX models
    raw = os.environ.get("DOWNLOAD_MODELS", "").strip()
    if not raw:
        print("ERROR: DOWNLOAD_MODELS is not set in .env", file=sys.stderr)
        sys.exit(1)
    models = [m.strip() for m in raw.split(",") if m.strip()]

    try:
        download_transformers_js()
    except Exception as e:
        print(f"ERROR downloading transformers.js: {e}", file=sys.stderr)
        sys.exit(1)

    try:
        download_frontend_libs()
    except Exception as e:
        print(f"ERROR downloading frontend libs: {e}", file=sys.stderr)
        sys.exit(1)

    failed = []
    for i, model_id in enumerate(models, 1):
        try:
            download_model(model_id, i, len(models))
        except Exception as e:
            print(f"  ERROR: {e}", file=sys.stderr)
            failed.append(model_id)

    succeeded = [m for m in models if m not in failed]
    write_models_available(succeeded)

    print("\n" + "=" * 50)
    if failed:
        print(f"Completed with errors. Failed: {failed}")
        sys.exit(1)
    else:
        print(f"All done! {len(models)} model(s) downloaded.")


if __name__ == "__main__":
    main()
